Env:
  WIDTH: 1200
  HEIGHT: 900
  NUM_CARS: 1
  FPS: 300

Car:
  IMAGE: images\car.png
  WIDTH: 22
  HEIGHT: 44
  MAX_SPEED: 25
  SPEED_UP: 1
  SLOW_DOWN: -2
  MIN_SPEED: 8
  TURN_ANGLE: 10

Max_speed_sign:
  IMAGE: images\max_speed_sign.png
  WIDTH: 24
  HEIGHT: 58

Min_speed_sign:
  IMAGE: images\min_speed_sign.png
  WIDTH: 24
  HEIGHT: 58

Map:
  ROAD_3:
    IMAGE: images\map_3.png
    SCENERY: images\map_3_scenery.png
    WIDTH: 800
    HEIGHT: 600
    START_POS:
      - X: 54
        Y: 540
        ANGLE: 0
