Env:
  WIDTH: 1200
  HEIGHT: 900
  NUM_CARS: 2
  FPS: 300

Car:
  IMAGE: images\car.png
  WIDTH: 22
  HEIGHT: 44
  MAX_SPEED: 20
  SPEED_UP: 2
  SLOW_DOWN: -3
  MIN_SPEED: 6
  TURN_ANGLE: 10

Max_speed_sign:
  IMAGE: images\max_speed_sign.png
  WIDTH: 24
  HEIGHT: 58

Min_speed_sign:
  IMAGE: images\min_speed_sign.png
  WIDTH: 24
  HEIGHT: 58

Map:
  ROAD_3:
    IMAGE: images\map_3.png
    SCENERY: images\map_3_scenery.png
    WIDTH: 800
    HEIGHT: 600
    START_POS:
      - X: 54
        Y: 540
        ANGLE: 0
    MIN_SPEED_SIGN_POS:
      - X1: 27
        Y1: 433
        X2: 91
        Y2: 433
      - X1: 280
        Y1: 224
        X2: 344
        Y2: 224
      - X1: 680
        Y1: 514
        X2: 744
        Y2: 514

    MAX_SPEED_SIGN_POS:
      - X1: 159
        Y1: 145
        X2: 227
        Y2: 145
      - X1: 440
        Y1: 223
        X2: 468
        Y2: 223

    SPEED_BUMP_POS:
      - X1: 26
        Y1: 441
        X2: 90
        Y2: 445
        X3: 87
        Y3: 474
        X4: 24
        Y4: 470
      - X1: 277
        Y1: 325
        X2: 341
        Y2: 325
        X3: 340
        Y3: 354
        X4: 275
        Y4: 354
      - X1: 415
        Y1: 520
        X2: 473
        Y2: 490
        X3: 485
        Y3: 517
        X4: 428
        Y4: 546
      - X1: 655
        Y1: 310
        X2: 681
        Y2: 45
        X3: 649
        Y3: 120
        X4: 622
        Y4: 89
